from typing import List, Dict, Any, Tuple

def validate_plan_dataflow(plan: List[Dict[str, Any]]) -> Tuple[bool, str]:
    """
    Validates the dataflow dependencies of a generated plan.

    It checks that for every step, the required input artifacts have been
    produced by a previous step in the plan. This prevents the agent from
    starting a plan with logical errors in its dataflow.

    Args:
        plan: The list of step dictionaries, as generated by the planner.

    Returns:
        A tuple containing a boolean (True if valid, False if invalid) and a
        status message.
    """
    produced_artifacts = set()
    for i, step in enumerate(plan):
        # Check the inputs required by the current step
        for param, artifact_name in step.get("inputs", {}).items():
            if artifact_name not in produced_artifacts:
                error_msg = (
                    f"Validation Error in Step {i+1} ('{step['task']}'): "
                    f"Input '{param}' requires artifact '{artifact_name}', "
                    "which is not produced by any preceding step."
                )
                return (False, error_msg)
        
        # Register the outputs of the current step for subsequent steps to use
        for artifact_name in step.get("outputs", []):
            # Optional: You could add a check here for duplicate artifact names
            # if you want to enforce that every artifact name is unique.
            produced_artifacts.add(artifact_name)
            
    return (True, "Plan dataflow is valid.")
